In [1]:
import pandas as pd

In [2]:
df = pd.read_excel('Crime_Data.xlsx')

In [3]:
df.columns

Index(['ID', 'Case Number', 'Date', 'Block', 'IUCR', 'Primary Type',
       'Description', 'Location Description', 'Arrest', 'Domestic', 'Beat',
       'District', 'Ward', 'Community Area', 'FBI Code', 'X Coordinate',
       'Y Coordinate', 'Year', 'Updated On', 'Latitude', 'Longitude',
       'Location'],
      dtype='object')

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 549999 entries, 0 to 549998
Data columns (total 22 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   ID                    549999 non-null  int64
 1   Case Number           549999 non-null  object
 2   Date                  549999 non-null  datetime64[ns]
 3   Block                 549999 non-null  object
 4   IUCR                  549999 non-null  object
 5   Primary Type          549999 non-null  object
 6   Description           549999 non-null  object
 7   Location Description  548326 non-null  object
 8   Arrest                549999 non-null  bool
 9   Domestic              549999 non-null  bool
 10  Beat                  549999 non-null  int64
 11  District              549999 non-null  int64
 12  Ward                  213674 non-null  float64
 13  Community Area        215093 non-null  float64
 14  FBI Code              549999 non-null  object
 15  X Coordinate          543087 non-null  float64
 16  Y Coordinate          543087 non-null  float64
 17  Year                  549999 non-null  int64
 18  Updated On            549999 non-null  datetime64[ns]
 19  Latitude              543087 non-null  float64
 20  Longitude             543087 non-null  float64
 21  Location              543087 non-null  object
dtypes: bool(2), datetime64[ns](2), float64(6), int64(4), object(8)
memory usage: 85.0+ MB

In [5]:
df.isnull().sum()

ID                           0
Case Number                  0
Date                         0
Block                        0
IUCR                         0
Primary Type                 0
Description                  0
Location Description      1673
Arrest                       0
Domestic                     0
Beat                         0
District                     0
Ward                    336325
Community Area          334906
FBI Code                     0
X Coordinate              6912
Y Coordinate              6912
Year                         0
Updated On                   0
Latitude                  6912
Longitude                 6912
Location                  6912
dtype: int64

In [6]:
df[df['Ward'].isnull()]

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
5,1930689,HH109118,2002-01-05 21:24:00,007XX E 103 ST,820,THEFT,$500 AND UNDER,GAS STATION,True,False,...,NaN,NaN,6,NaN,NaN,2002,2016-02-04 06:33:39,NaN,NaN,NaN
3354,1387435,G098599,2001-02-17 18:15:00,012XX S LAKE SHORE DR,031A,ROBBERY,ARMED: HANDGUN,OTHER,True,False,...,NaN,NaN,3,NaN,NaN,2001,2015-08-17 15:03:40,NaN,NaN,NaN
4747,1555581,G311820,2001-05-29 23:30:00,012XX W ESTES AV,1320,CRIMINAL DAMAGE,TO VEHICLE,STREET,False,False,...,NaN,NaN,14,NaN,NaN,2001,2015-08-17 15:03:40,NaN,NaN,NaN
4824,1605630,G377246,2001-06-28 16:50:00,025XX S EMERALD AV,810,THEFT,OVER $500,STREET,False,False,...,NaN,NaN,6,NaN,NaN,2001,2015-08-17 15:03:40,NaN,NaN,NaN
4825,1612453,G386076,2001-07-02 17:29:40,005XX E OHIO ST,560,ASSAULT,SIMPLE,PARK PROPERTY,True,False,...,NaN,NaN,08A,NaN,NaN,2001,2015-08-17 15:03:40,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
549994,1715153,G516233,2001-08-27 23:00:00,036XX S LAKE PARK AV,4387,OTHER OFFENSE,VIOLATE ORDER OF PROTECTION,RESIDENCE,False,True,...,NaN,NaN,26,1182305.0,1881212.0,2001,2015-08-17 15:03:40,41.829265,-87.606630,"(41.829264761, -87.606629868)"
549995,1799889,G625392,2001-10-16 16:30:00,065XX S STEWART AV,610,BURGLARY,FORCIBLE ENTRY,APARTMENT,False,False,...,NaN,NaN,5,1174713.0,1861451.0,2001,2015-08-17 15:03:40,41.775211,-87.635073,"(41.775211478, -87.635073388)"
549996,1769834,G583569,2001-09-29 05:35:00,031XX N CENTRAL PARK AV,460,BATTERY,SIMPLE,RESIDENCE,False,True,...,NaN,NaN,08B,1151878.0,1920763.0,2001,2015-08-17 15:03:40,41.938449,-87.717224,"(41.938448908, -87.717224032)"
549997,1788327,G610965,2001-09-12 09:05:00,065XX S CICERO AV,910,MOTOR VEHICLE THEFT,AUTOMOBILE,OTHER,True,False,...,NaN,NaN,7,1145544.0,1861043.0,2001,2015-08-17 15:03:40,41.774692,-87.742015,"(41.774692006, -87.742014699)"
549998,1810693,G627247,2001-10-18 17:34:00,053XX W FERDINAND ST,2092,NARCOTICS,SOLICIT NARCOTICS ON PUBLICWAY,SIDEWALK,True,False,...,NaN,NaN,26,1140670.0,1902673.0,2001,2015-08-17 15:03:40,41.889022,-87.758862,"(41.889021585, -87.758861788)"

In [7]:
df['Location'].unique().tolist()

[nan,
 '(41.917838056, -87.755968972)',
 '(41.995219444, -87.713354912)',
 '(41.952345086, -87.677975059)',
 '(41.737750767, -87.604855911)',
 '(41.886018055, -87.633937881)',
 '(41.877565108, -87.68479102)',
 '(41.7619185, -87.576209245)',
 '(41.943378528, -87.7199738)',
 '(41.796477414, -87.708540915)',
 '(41.752688801, -87.704908791)',
 '(41.758126171, -87.631582508)',
 '(41.731497731, -87.658074565)',
 '(41.764827083, -87.671709119)',
 '(41.837651929, -87.641404086)',
 '(41.880594385, -87.702959421)',
 '(41.880779076, -87.721377025)',
 '(41.915187259, -87.775425225)',
 '(41.952036311, -87.646281883)',
 '(41.898884591, -87.734196199)',
 '(41.699971107, -87.532866422)',
 '(41.89850206, -87.69924242)',
 '(41.705956552, -87.648373487)',
 '(41.749500329, -87.6011574)',
 '(41.745882542, -87.597167639)',
 '(41.746626309, -87.618031954)',
 '(41.736409029, -87.562410309)',
 '(41.771782439, -87.649436929)',
 '(41.899206068, -87.705505587)',
 '(41.763337967, -87.597001131)',
 '(41.985875279, -87.766403857)',
 '(41.76261474, -87.652840463)',
 '(41.89621515, -87.728572048)',
 '(41.748653803, -87.602680492)',
 '(41.932015426, -87.769916668)',
 '(41.917562778, -87.749828117)',
 '(41.91065261, -87.66614577)',
 '(41.692833841, -87.60431945)',
 '(41.80890316, -87.618139193)',
 '(41.911574252, -87.789972279)',
 '(41.788264552, -87.62229949)',
 '(41.917656022, -87.688750258)',
 '(41.935883156, -87.716219645)',
 '(41.917790125, -87.754624625)',
 '(41.917506742, -87.753392641)',
 '(41.910962378, -87.694559852)',
 '(41.921207741, -87.754832585)',
 '(41.929743818, -87.684273777)',
 '(41.903304304, -87.670064675)',
 '(41.924248302, -87.745636923)',
 '(41.972359593, -87.728142793)',
 '(41.969229299, -87.713386363)',
 '(41.928235818, -87.682084152)',
 '(41.910107045, -87.707676543)',
 '(41.761701305, -87.718642841)',
 '(41.9301323, -87.785676799)',
 '(41.906519104, -87.758359629)',
 '(41.928869943, -87.725672915)',
 '(41.926287021, -87.785547998)',
 '(41.903125362, -87.680983903)',
 '(41.748232929, -87.641533277)',
 '(41.909687183, -87.796009633)',
 '(41.71286177, -87.537694886)',
 '(41.910491438, -87.749936608)',
 '(41.763423571, -87.705236576)',
 '(41.98142637, -87.772997369)',
 '(41.796510344, -87.708540596)',
 '(41.945583621, -87.747047365)',
 '(41.961202055, -87.777049892)',
 '(41.988962585, -87.782770866)',
 '(41.915389329, -87.765701742)',
 '(41.91943601, -87.775564587)',
 '(41.902562633, -87.750879383)',
 '(41.910505437, -87.676316472)',
 '(41.862914501, -87.709737438)',
 '(41.873191445, -87.743446563)',
 '(41.755353249, -87.651440192)',
 '(41.965906449, -87.708395773)',
 '(41.807145524, -87.741921764)',
 '(41.803995088, -87.741389571)',
 '(41.654834273, -87.607558429)',
 '(41.807646537, -87.741157889)',
 '(41.752935445, -87.5490632)',
 '(41.992785149, -87.71893317)',
 '(41.778099133, -87.633828531)',
 '(41.774140355, -87.599707766)',
 '(41.973339203, -87.653132052)',
 '(41.80805312, -87.709103358)',
 '(41.751497379, -87.710886632)',
 '(41.866147762, -87.68602617)',
 '(41.941544345, -87.667566063)',
 '(41.763740729, -87.590930221)',
 '(41.955482844, -87.74667356)',
 '(41.902691497, -87.640639866)',
 '(41.75953427, -87.60907381)',
 '(41.711760405, -87.599842499)',
 '(41.907130946, -87.694473144)',
 '(41.818970326, -87.642544391)',
 '(41.746431352, -87.646345733)',
 '(41.760296965, -87.684345797)',
 '(41.779881706, -87.636789913)',
 '(41.853058663, -87.650190508)',
 '(41.843879386, -87.620432585)',
 '(41.858686589, -87.631890095)',
 '(41.935409279, -87.74675098)',
 '(41.968462532, -87.707613294)',
 '(41.96607814, -87.647153241)',
 '(41.736277091, -87.585212192)',
 '(41.763659945, -87.626863438)',
 '(41.891943951, -87.768770463)',
 '(41.748776618, -87.605167356)',
 '(41.769925563, -87.637267875)',
 '(41.913472752, -87.764370362)',
 '(41.809803372, -87.64556634)',
 '(41.98715762, -87.668356321)',
 '(41.806060798, -87.590999348)',
 '(41.939051438, -87.730438917)',
 '(42.013787643, -87.673182834)',
 '(42.000299008, -87.807981016)',
 '(41.768891175, -87.614133593)',
 '(41.872963554, -87.753663295)',
 '(41.880414105, -87.72811149)',
 '(41.702027818, -87.563981957)',
 '(41.902642474, -87.728111001)',
 '(41.805309638, -87.58899806)',
 '(41.887771177, -87.644304667)',
 '(41.973922349, -87.67934257)',
 '(41.853842942, -87.623842041)',
 '(41.776724154, -87.687234143)',
 '(41.897618116, -87.769139223)',
 '(41.920848651, -87.7731786)',
 '(41.855190551, -87.623871195)',
 '(41.967222325, -87.709662541)',
 '(41.788524411, -87.619066119)',
 '(41.884476226, -87.631310613)',
 '(41.754476149, -87.56507476)',
 '(41.872844469, -87.699441004)',
 '(41.782211626, -87.698354554)',
 '(41.686267711, -87.61979192)',
 '(41.980782106, -87.666808076)',
 '(41.9206596, -87.740444827)',
 '(41.754730716, -87.686637486)',
 '(41.921470593, -87.732801776)',
 '(41.883028274, -87.761636626)',
 '(41.81797649, -87.7239343)',
 '(41.813833962, -87.616712397)',
 '(41.974187006, -87.656355545)',
 '(41.731921758, -87.615304512)',
 '(41.694019253, -87.655405714)',
 '(41.878604157, -87.685096307)',
 '(41.692029295, -87.605979811)',
 '(41.754639362, -87.676820054)',
 '(41.745069714, -87.613545708)',
 '(41.768002049, -87.618535016)',
 '(41.971872921, -87.692568932)',
 '(41.755364837, -87.565826474)',
 '(41.961102078, -87.767263264)',
 '(41.787670818, -87.64741635)',
 '(41.783092808, -87.60844576)',
 '(41.963070794, -87.655984213)',
 '(41.752558184, -87.716252667)',
 '(41.665814864, -87.558853882)',
 '(41.891193453, -87.755812324)',
 '(41.866286618, -87.715725607)',
 '(41.894008903, -87.751434582)',
 '(41.967648053, -87.693769564)',
 '(41.851487667, -87.728776988)',
 '(41.905991963, -87.678375871)',
 '(41.96203391, -87.645898728)',
 '(41.761189159, -87.65401376)',
 '(41.743255632, -87.601367592)',
 '(41.680916759, -87.632359783)',
 '(41.868541914, -87.639235361)',
 '(41.917309067, -87.714473331)',
 '(41.83368122, -87.612439993)',
 '(41.930492323, -87.710917158)',
 '(41.771676658, -87.572388286)',
 '(41.789717304, -87.625576333)',
 '(41.857307384, -87.644778606)',
 '(41.995366855, -87.684902319)',
 '(41.947428137, -87.747126039)',
 '(41.868234232, -87.704953287)',
 '(41.976182125, -87.876421145)',
 '(41.71345022, -87.570236958)',
 '(42.014911903, -87.671128898)',
 '(41.812708431, -87.60444003)',
 '(41.70399846, -87.620617627)',
 '(41.945560284, -87.707282238)',
 '(41.909959349, -87.638555401)',
 '(41.981219319, -87.783525344)',
 '(41.849666532, -87.631940932)',
 '(41.946809107, -87.682641363)',
 '(41.734833707, -87.663040714)',
 '(41.724768174, -87.628740293)',
 '(41.745316916, -87.59412899)',
 '(41.752727431, -87.568687129)',
 '(42.002575704, -87.65915619)',
 '(41.874119819, -87.624223667)',
 '(41.99812694, -87.66612678)',
 '(41.899476558, -87.72620879)',
 '(41.950491896, -87.649595954)',
 '(41.96498423, -87.758246066)',
 '(41.803799227, -87.590530312)',
 '(41.893646656, -87.631177143)',
 '(41.984109031, -87.660855375)',
 '(41.735162406, -87.703683752)',
 '(41.771225099, -87.685863303)',
 '(41.771113236, -87.722567122)',
 '(41.943967854, -87.669999929)',
 '(41.717843335, -87.561119489)',
 '(41.749058639, -87.560126182)',
 '(41.684796684, -87.720096595)',
 '(41.726566477, -87.636065622)',
 '(41.902394222, -87.626978162)',
 '(41.702244602, -87.563979373)',
 '(41.828499363, -87.64361241)',
 '(41.758524942, -87.60872964)',
 '(41.907050205, -87.663450096)',
 '(41.935432921, -87.668504341)',
 '(41.998734156, -87.660613118)',
 '(41.91715988, -87.727147152)',
 '(41.880515138, -87.743841898)',
 '(41.949050296, -87.706663599)',
 '(41.899145291, -87.627910223)',
 '(41.867081407, -87.619003708)',
 '(41.745121812, -87.601375711)',
 '(41.938268503, -87.832461653)',
 '(41.7478257, -87.646385835)',
 '(41.891893989, -87.706752484)',
 '(41.974861952, -87.890372151)',
 '(41.808990794, -87.70642393)',
 '(41.753307626, -87.667154745)',
 '(41.807851044, -87.725149)',
 '(41.955736616, -87.656168497)',
 '(41.776589139, -87.675052781)',
 '(41.868116071, -87.632378118)',
 '(41.800740861, -87.651399312)',
 '(41.865397377, -87.640660777)',
 '(41.813986532, -87.61258752)',
 '(42.005384054, -87.709326751)',
 '(41.817822779, -87.72392842)',
 '(42.007893607, -87.66661712)',
 '(41.881998832, -87.729400168)',
 '(41.877532811, -87.672387519)',
 '(41.744081763, -87.670562675)',
 '(41.897131925, -87.656791646)',
 '(41.662944028, -87.641411276)',
 '(41.949640684, -87.712796874)',
 '(41.866853689, -87.712996017)',
 '(41.909524018, -87.753986578)',
 '(41.786343156, -87.697609774)',
 '(41.718823567, -87.643141787)',
 '(41.779618399, -87.653767961)',
 '(41.793390915, -87.711728299)',
 '(41.780036279, -87.604637829)',
 '(41.807499342, -87.590234482)',
 '(41.731859652, -87.554778427)',
 '(41.881088655, -87.720764494)',
 '(41.744973301, -87.596602719)',
 '(41.700134558, -87.561983199)',
 '(41.918320935, -87.705237426)',
 '(41.727872617, -87.551207132)',
 '(41.761830729, -87.627510276)',
 '(41.80171934, -87.630703621)',
 '(41.867428687, -87.626342565)',
 '(41.929925166, -87.746525605)',
 '(41.685074357, -87.642774065)',
 '(41.765254159, -87.641255151)',
 '(41.871336669, -87.625925)',
 '(41.973046564, -87.7709563)',
 '(41.883267969, -87.712150552)',
 '(41.807135535, -87.589992936)',
 '(41.763358065, -87.717468752)',
 '(41.806890268, -87.589834384)',
 '(41.92537055, -87.725577509)',
 '(41.982603849, -87.696713091)',
 '(41.751317167, -87.563800456)',
 '(41.91081797, -87.654560398)',
 '(41.982963773, -87.716905397)',
 '(41.917336596, -87.712455913)',
 '(41.749224132, -87.577157314)',
 '(41.800772595, -87.673275953)',
 '(41.855522867, -87.680843862)',
 '(41.789994324, -87.652338285)',
 '(41.751742742, -87.661860682)',
 '(41.883092889, -87.650384784)',
 '(41.95659747, -87.700766117)',
 '(41.801607877, -87.739324672)',
 '(41.926346433, -87.724859021)',
 '(41.928076536, -87.785606186)',
 '(41.681024396, -87.614684538)',
 '(41.890756989, -87.636133879)',
 '(41.744278483, -87.647500963)',
 '(41.758509638, -87.609349222)',
 '(41.913110178, -87.633208656)',
 '(41.716563317, -87.564629081)',
 '(41.872682495, -87.714015459)',
 '(41.822130356, -87.603276576)',
 '(41.794672085, -87.623570871)',
 '(41.788987036, -87.74147999)',
 '(41.965905724, -87.645397479)',
 '(41.858965656, -87.71585846)',
 '(41.953916833, -87.70836586)',
 '(41.76520694, -87.610413911)',
 '(41.80859321, -87.665577234)',
 '(41.893812529, -87.624229924)',
 '(41.944386341, -87.727337759)',
 '(41.883088627, -87.763288609)',
 '(41.89221925, -87.604682647)',
 '(41.879225851, -87.646636417)',
 '(41.996363572, -87.703238225)',
 '(41.8225226, -87.690494093)',
 '(41.891694878, -87.626155832)',
 '(41.848845969, -87.629244886)',
 '(41.739552385, -87.602475891)',
 '(41.807672926, -87.675879062)',
 '(42.006922562, -87.670001247)',
 '(42.001552964, -87.659299433)',
 '(41.812579436, -87.604437824)',
 '(41.745905086, -87.549141439)',
 '(41.78205732, -87.70322518)',
 '(41.702218321, -87.530450967)',
 '(41.721840482, -87.617277592)',
 '(41.960201886, -87.683791965)',
 '(41.901631293, -87.709408616)',
 '(41.737094305, -87.572998178)',
 '(41.939509837, -87.764892445)',
 '(41.727274127, -87.587917642)',
 '(41.868494355, -87.683641769)',
 '(41.722385161, -87.581812836)',
 '(41.871834768, -87.62615082)',
 '(41.880988964, -87.704854042)',
 '(41.976310466, -87.689166788)',
 '(41.797399927, -87.620914942)',
 '(41.870028132, -87.708823855)',
 '(41.707756212, -87.580708771)',
 '(41.737731152, -87.654997489)',
 '(41.721183199, -87.56235057)',
 '(41.90075729, -87.731787389)',
 '(41.711810762, -87.639319919)',
 '(41.866810739, -87.625817031)',
 '(41.923422944, -87.730413365)',
 '(41.793195202, -87.687688498)',
 '(41.861699337, -87.722605232)',
 '(41.902923197, -87.697288509)',
 '(41.904837592, -87.687751444)',
 '(41.744991196, -87.717614993)',
 '(41.997573831, -87.698767532)',
 '(41.75898158, -87.663632474)',
 '(42.011281985, -87.681789636)',
 '(41.767508679, -87.683320046)',
 '(41.899379012, -87.755709189)',
 '(41.892474929, -87.71622631)',
 '(41.90982859, -87.677447594)',
 '(41.793102569, -87.65727433)',
 '(41.749880266, -87.663426578)',
 '(41.879996761, -87.761814204)',
 '(41.796936356, -87.661018732)',
 '(41.774953436, -87.636868902)',
 '(42.000265632, -87.699715722)',
 '(41.967040741, -87.781963169)',
 '(41.965423179, -87.655621013)',
 '(41.691339972, -87.677493383)',
 '(41.927899924, -87.747062318)',
 '(41.780415657, -87.605608794)',
 '(41.87968721, -87.731830814)',
 '(41.905068825, -87.747241853)',
 '(41.834690813, -87.613705645)',
 '(41.887739656, -87.763746728)',
 '(41.869244422, -87.62707888)',
 '(41.944705219, -87.789948362)',
 '(41.9410841, -87.647649169)',
 '(41.908347446, -87.668509926)',
 '(41.907420613, -87.685925328)',
 '(41.682343181, -87.662604657)',
 '(41.961692571, -87.661480876)',
 '(41.932755165, -87.647150367)',
 '(41.754441912, -87.633601696)',
 '(41.785687563, -87.616541923)',
 '(41.844252757, -87.724943845)',
 '(41.915010762, -87.682457437)',
 '(41.807049263, -87.591930589)',
 '(41.651250849, -87.547162057)',
 '(41.742274536, -87.651087579)',
 '(41.918612938, -87.708963978)',
 '(41.941748603, -87.668718084)',
 '(41.691974413, -87.605980429)',
 '(41.707519433, -87.601839023)',
 '(41.76625017, -87.640771585)',
 '(41.938127563, -87.731138599)',
 '(41.677799762, -87.642881123)',
 '(41.800786864, -87.620994789)',
 '(41.892251677, -87.772205489)',
 '(41.769712828, -87.584666196)',
 '(41.886393351, -87.765080772)',
 '(41.970027594, -87.696294098)',
 '(41.975267479, -87.753475707)',
 '(41.871838775, -87.726117926)',
 '(41.986181172, -87.658097002)',
 '(41.906507737, -87.679795958)',
 '(41.856051578, -87.628218813)',
 '(41.939224931, -87.716602756)',
 '(41.926497977, -87.711147073)',
 '(41.938825971, -87.807986017)',
 '(41.788547837, -87.741458362)',
 '(41.911880784, -87.764307348)',
 '(41.807030055, -87.591930811)',
 '(41.960028926, -87.706989887)',
 '(41.698541312, -87.532865844)',
 '(41.729006364, -87.558142967)',
 '(41.896772914, -87.621464432)',
 '(41.760720857, -87.652787167)',
 '(41.87188334, -87.704315401)',
 '(41.881624191, -87.629391908)',
 '(41.897012256, -87.632716018)',
 '(41.843892459, -87.622098627)',
 '(41.953436358, -87.746273229)',
 '(41.756518432, -87.583430519)',
 '(41.921021491, -87.69730355)',
 '(41.947183891, -87.688269091)',
 '(41.764487502, -87.696110119)',
 '(41.72192149, -87.682094682)',
 '(41.801102138, -87.687315724)',
 '(41.954704646, -87.720626224)',
 '(41.95273487, -87.714082963)',
 '(42.014981628, -87.667054591)',
 '(41.998103671, -87.668264445)',
 '(41.655594621, -87.596798862)',
 '(41.803661521, -87.583695281)',
 '(42.012205212, -87.693709742)',
 '(41.755908546, -87.65763916)',
 '(41.976290414, -87.905227221)',
 '(41.782132982, -87.702010828)',
 '(41.856829444, -87.669880705)',
 '(41.854273371, -87.624663171)',
 '(41.866184155, -87.72428806)',
 '(41.897924825, -87.724937898)',
 '(41.945863902, -87.767912706)',
 '(41.879060101, -87.626107881)',
 '(41.897032275, -87.664138817)',
 '(41.913930301, -87.636752477)',
 '(41.882219372, -87.677546419)',
 '(41.807763621, -87.602339331)',
 '(41.880834047, -87.679080847)',
 '(41.931962854, -87.712876373)',
 '(41.865035371, -87.62941605)',
 '(41.938204223, -87.710022552)',
 '(41.672333016, -87.643334855)',
 '(41.798945386, -87.654986779)',
 '(41.955190155, -87.751712919)',
 '(41.944749075, -87.656681766)',
 '(41.983381702, -87.708931089)',
 '(41.745454358, -87.699830848)',
 '(41.910291883, -87.689974258)',
 '(41.902437713, -87.687011559)',
 '(41.754787799, -87.576054836)',
 '(41.685826775, -87.620821877)',
 '(41.870718789, -87.632569976)',
 '(41.911367051, -87.626401638)',
 '(41.69073279, -87.626461055)',
 '(41.966018559, -87.710847252)',
 '(41.958506815, -87.648061706)',
 '(41.799749186, -87.751499618)',
 '(41.706875037, -87.628265515)',
 '(41.659189752, -87.555156663)',
 '(41.88732762, -87.758160825)',
 '(41.795760253, -87.65005855)',
 '(41.761484638, -87.55806373)',
 '(41.698696274, -87.563172144)',
 '(41.755239277, -87.673277249)',
 '(41.891303157, -87.628055281)',
 '(42.003574794, -87.681522434)',
 '(41.937227668, -87.644305471)',
 '(41.766490771, -87.641989643)',
 '(41.809081165, -87.633674979)',
 '(42.015164168, -87.697297389)',
 '(41.769350572, -87.614747976)',
 '(41.909189095, -87.651058196)',
 '(41.933433923, -87.641362086)',
 '(41.851430749, -87.724754706)',
 '(41.916855183, -87.694728891)',
 '(41.946316385, -87.731675415)',
 '(41.766062984, -87.681963712)',
 '(41.993558695, -87.655495503)',
 '(41.903133353, -87.680458524)',
 '(41.953497705, -87.647905817)',
 '(41.990332555, -87.781184693)',
 '(41.872894484, -87.627560076)',
 '(41.794340626, -87.715833715)',
 '(41.732787885, -87.565890141)',
 '(41.778661058, -87.68227253)',
 '(41.883257356, -87.669541269)',
 '(41.881933769, -87.701995157)',
 '(41.874060099, -87.705924314)',
 '(41.750757383, -87.636034766)',
 '(41.942848288, -87.769086168)',
 '(41.648588776, -87.539964437)',
 '(41.801709383, -87.596697686)',
 '(41.766427022, -87.631026525)',
 '(42.012048033, -87.700503994)',
 '(41.887988672, -87.625469546)',
 '(41.666119868, -87.641516349)',
 '(41.885700244, -87.641726854)',
 '(41.883500187, -87.627876698)',
 '(41.72853976, -87.59736201)',
 '(41.896774009, -87.640942565)',
 '(41.88683958, -87.70383084)',
 '(41.793703259, -87.693147462)',
 '(41.736944201, -87.650938817)',
 '(41.72292995, -87.605913481)',
 '(41.784740334, -87.622210098)',
 '(41.736582312, -87.57692092)',
 '(41.928408571, -87.70420874)',
 '(41.977978764, -87.69899153)',
 '(41.718957929, -87.56568476)',
 '(41.793223108, -87.65120397)',
 '(41.895013678, -87.675740686)',
 '(41.755412283, -87.562256233)',
 '(41.922467354, -87.779319275)',
 '(41.762475016, -87.708434706)',
 '(41.891118758, -87.686706987)',
 '(41.893281677, -87.627596446)',
 '(41.699999944, -87.563189544)',
 '(41.767973069, -87.577142454)',
 '(41.988956425, -87.718826534)',
 '(41.774973026, -87.68963101)',
 '(41.87741656, -87.697982127)',
 '(41.74938411, -87.653709473)',
 '(41.873855191, -87.762379293)',
 '(41.814969058, -87.669993754)',
 '(41.748060338, -87.741302702)',
 '(41.695308608, -87.62395405)',
 '(41.894824927, -87.631788635)',
 '(41.774200754, -87.62152367)',
 '(41.74932776, -87.555274664)',
 '(41.947997344, -87.79851488)',
 '(41.895449977, -87.653584531)',
 '(41.903168666, -87.678467174)',
 '(41.695908161, -87.595822806)',
 '(41.767036006, -87.582809521)',
 '(41.898922292, -87.731958884)',
 '(41.958474197, -87.65087832)',
 '(41.79736226, -87.582679493)',
 '(41.735066839, -87.650896405)',
 '(41.893865381, -87.768863729)',
 '(41.947285426, -87.747123671)',
 '(41.707886031, -87.606416363)',
 '(41.786903184, -87.622266865)',
 '(41.75276137, -87.580894222)',
 '(41.987292267, -87.658979074)',
 '(41.850601726, -87.635898418)',
 '(41.694393194, -87.624147184)',
 '(41.740127827, -87.555121917)',
 '(41.819767809, -87.600302468)',
 '(41.995939349, -87.688126446)',
 '(41.905833996, -87.638427474)',
 '(41.783451628, -87.70326286)',
 '(41.74588634, -87.596903757)',
 '(41.963478472, -87.664201385)',
 '(41.886530514, -87.697047165)',
 '(41.784732839, -87.629011797)',
 '(41.739558418, -87.612991694)',
 '(41.739897121, -87.735687345)',
 '(41.95024738, -87.782791674)',
 '(41.878386896, -87.692347019)',
 '(41.812373584, -87.604432822)',
 '(41.882931813, -87.692918534)',
 '(41.959354838, -87.653611694)',
 '(41.74981542, -87.650084246)',
 '(41.935970935, -87.745499907)',
 '(41.748472119, -87.603888197)',
 '(41.901267916, -87.752073955)',
 '(41.792831954, -87.591628734)',
 '(41.700551523, -87.658332506)',
 '(41.885702079, -87.642031644)',
 '(41.887521986, -87.624552898)',
 '(41.804695984, -87.633253215)',
 '(41.903299855, -87.670244719)',
 '(41.858880162, -87.654977778)',
 '(41.873242815, -87.725407013)',
 '(41.765652804, -87.618073574)',
 '(41.805577741, -87.590564785)',
 '(41.89067449, -87.685785948)',
 '(41.99157427, -87.655431953)',
 '(41.888709801, -87.713673374)',
 '(41.983638813, -87.694315735)',
 '(41.939919138, -87.653410162)',
 '(41.806063471, -87.590988314)',
 '(42.017676014, -87.665569188)',
 '(41.812378587, -87.608258712)',
 '(41.995602717, -87.672844745)',
 '(41.950872498, -87.730764998)',
 '(41.913060734, -87.678310956)',

In [8]:
d = df.loc[(df['Location'] == '(41.877565108, -87.68479102)') & (df['Ward'])]

In [9]:
d

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
7,13210088,JG423627,2023-08-31 12:00:00,023XX W JACKSON BLVD,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,STREET,False,False,...,27.0,28.0,11,1160870.0,1898642.0,2023,2023-09-16 15:41:56,41.877565,-87.684791,"(41.877565108, -87.68479102)"
6055,13209778,JG422814,2023-09-13 16:16:00,023XX W JACKSON BLVD,486,BATTERY,DOMESTIC BATTERY SIMPLE,APARTMENT,False,True,...,27.0,28.0,08B,1160870.0,1898642.0,2023,2023-09-21 15:42:06,41.877565,-87.684791,"(41.877565108, -87.68479102)"
38877,13261044,JG484618,2023-09-18 08:00:00,023XX W JACKSON BLVD,1140,DECEPTIVE PRACTICE,EMBEZZLEMENT,APARTMENT,False,False,...,27.0,28.0,12,1160870.0,1898642.0,2023,2023-11-01 15:40:30,41.877565,-87.684791,"(41.877565108, -87.68479102)"
76275,13304363,JG536813,2023-12-11 10:45:00,023XX W JACKSON BLVD,560,ASSAULT,SIMPLE,CHA HALLWAY / STAIRWELL / ELEVATOR,False,False,...,27.0,28.0,08A,1160870.0,1898642.0,2023,2023-12-19 15:46:54,41.877565,-87.684791,"(41.877565108, -87.68479102)"
78097,13307370,JG540408,2023-12-14 07:30:00,023XX W JACKSON BLVD,460,BATTERY,SIMPLE,CHA APARTMENT,False,False,...,27.0,28.0,08B,1160870.0,1898642.0,2023,2023-12-22 15:41:15,41.877565,-87.684791,"(41.877565108, -87.68479102)"
85557,13318182,JG553373,2023-12-24 15:00:00,023XX W JACKSON BLVD,486,BATTERY,DOMESTIC BATTERY SIMPLE,RESIDENCE,False,True,...,27.0,28.0,08B,1160870.0,1898642.0,2023,2024-01-01 15:41:08,41.877565,-87.684791,"(41.877565108, -87.68479102)"
118899,13366856,JH150094,2024-02-12 05:20:00,023XX W JACKSON BLVD,620,BURGLARY,UNLAWFUL ENTRY,APARTMENT,False,False,...,27.0,28.0,5,1160870.0,1898642.0,2024,2024-02-20 15:41:53,41.877565,-87.684791,"(41.877565108, -87.68479102)"
141050,13399008,JH188719,2024-03-14 20:30:00,023XX W JACKSON BLVD,820,THEFT,$500 AND UNDER,STREET,False,False,...,27.0,28.0,6,1160870.0,1898642.0,2024,2024-03-22 15:50:48,41.877565,-87.684791,"(41.877565108, -87.68479102)"
146206,13383990,JH170344,2024-02-29 13:40:00,023XX W JACKSON BLVD,486,BATTERY,DOMESTIC BATTERY SIMPLE,APARTMENT,False,True,...,27.0,28.0,08B,1160870.0,1898642.0,2024,2024-03-30 15:40:59,41.877565,-87.684791,"(41.877565108, -87.68479102)"
152041,13413902,JH206526,2024-03-30 09:15:00,023XX W JACKSON BLVD,2820,OTHER OFFENSE,TELEPHONE THREAT,APARTMENT,False,False,...,27.0,28.0,08A,1160870.0,1898642.0,2024,2024-04-07 15:40:59,41.877565,-87.684791,"(41.877565108, -87.68479102)"
154328,13418305,JH211594,2024-04-02 21:00:00,023XX W JACKSON BLVD,486,BATTERY,DOMESTIC BATTERY SIMPLE,APARTMENT,False,True,...,27.0,28.0,08B,1160870.0,1898642.0,2024,2024-04-10 15:41:06,41.877565,-87.684791,"(41.877565108, -87.68479102)"
180833,13457113,JH259523,2024-05-11 17:19:00,023XX W JACKSON BLVD,486,BATTERY,DOMESTIC BATTERY SIMPLE,CHA APARTMENT,False,True,...,27.0,28.0,08B,1160870.0,1898642.0,2024,2024-05-19 15:41:04,41.877565,-87.684791,"(41.877565108, -87.68479102)"
186537,13466203,JH269887,2024-05-19 13:01:00,023XX W JACKSON BLVD,486,BATTERY,DOMESTIC BATTERY SIMPLE,APARTMENT,False,True,...,27.0,28.0,08B,1160870.0,1898642.0,2024,2024-05-27 15:41:20,41.877565,-87.684791,"(41.877565108, -87.68479102)"